# Generated by Django 3.2.5 on 2021-07-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='ID пользователя')),
                ('name', models.TextField(verbose_name='Имя пользователя')),
                ('surname', models.TextField(verbose_name='Фамилия пользователя')),
                ('first_start', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Профиль',
            },
        ),
    ]
